import turtle
turtle.showturtle()
turtle.fillcolor('black')
turtle.begin_fill()
turtle.circle(5)
turtle.end_fill()
turtle.right(45)
turtle.forward(200)
turtle.fillcolor('black')
turtle.begin_fill()
turtle.circle(5)
turtle.end_fill()
turtle.right(180)
turtle.forward(400)
turtle.fillcolor('black')
turtle.begin_fill()
turtle.circle(5)
turtle.end_fill()
turtle.right(225)
#Linestart
turtle.forward(20)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.forward(45)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.forward(45)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.forward(45)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(20)

turtle.begin_fill()
turtle.circle(5)
turtle.end_fill()

turtle.left(90)
turtle.forward(20)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.forward(45)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.forward(45)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.forward(45)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(20)

turtle.begin_fill()
turtle.circle(5)
turtle.end_fill()

turtle.left(90)
turtle.forward(20)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.forward(45)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.forward(45)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.forward(45)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(20)

turtle.begin_fill()
turtle.circle(5)
turtle.end_fill()


turtle.left(90)
turtle.forward(20)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.forward(45)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.forward(45)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.forward(45)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(20)

turtle.penup()
turtle.goto(0,0)
turtle.pendown()



turtle.left(45)
turtle.forward(200)

turtle.left(180)
turtle.forward(400)

turtle.left(225)
turtle.done()